#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

export DATABASE_URL="mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"

# check connect resource
python << END
import sys
import pymysql
import redis
import time

MYSQL_CONNECT_STATUS = False
REDIS_CONNECT_STATUS = False
OK = 0
WARNING = 1

countdown = 60

for _ in range(countdown):
    if MYSQL_CONNECT_STATUS and REDIS_CONNECT_STATUS:
        sys.exit(OK)
    if not MYSQL_CONNECT_STATUS:
        try:
            conn = pymysql.connect(
                host="${DATABASE_HOST}",
                port=${DATABASE_PORT},
                db="${DATABASE_NAME}",
                user="${DATABASE_USER}",
                password="${DATABASE_PASSWORD}",
            )
            MYSQL_CONNECT_STATUS = True
            print("MYSQL is available")

        except Exception as e:
            print("Waiting for MYSQL available...")

    if not REDIS_CONNECT_STATUS:
        try:
            redis_conn = redis.Redis(host="${REDIS_HOST}", port="${REDIS_PORT}", db="${REDIS_DB}", password="${REDIS_PASSWORD}")
            redis_conn.ping()
            print("REDIS is available")
            REDIS_CONNECT_STATUS = True
        except Exception as e:
            print("Waiting for REDIS available...")

    time.sleep(1)

print("Can't connect resource")
sys.exit(WARNING)
END

exec "$@"
