from rest_framework.status import HTTP_400_BAD_REQUEST, HTTP_404_NOT_FOUND

ERROR_GROUP_DOES_NOT_EXIST = (
    "ERROR_GROUP_DOES_NOT_EXIST",
    HTTP_404_NOT_FOUND,
    "The requested group does not exist.",
)
ERROR_USER_INVALID_GROUP_PERMISSIONS = (
    "ERROR_USER_INVALID_GROUP_PERMISSIONS",
    HTTP_400_BAD_REQUEST,
    "You need {e.permissions} permissions.",
)
ERROR_USER_NOT_IN_GROUP = "ERROR_USER_NOT_IN_GROUP"
BAD_TOKEN_SIGNATURE = "BAD_TOKEN_SIGNATURE"
EXPIRED_TOKEN_SIGNATURE = "EXPIRED_TOKEN_SIGNATURE"
ERROR_HOSTNAME_IS_NOT_ALLOWED = (
    "ERROR_HOSTNAME_IS_NOT_ALLOWED",
    HTTP_400_BAD_REQUEST,
    "Only the hostname of the web frontend is allowed.",
)

ERROR_ALREADY_EXISTS = "ERROR_EMAIL_ALREADY_EXISTS"
ERROR_USER_NOT_FOUND = "ERROR_USER_NOT_FOUND"
ERROR_INVALID_OLD_PASSWORD = "ERROR_INVALID_OLD_PASSWORD"
ERROR_DISABLED_SIGNUP = "ERROR_DISABLED_SIGNUP"
ERROR_INVALID_PIN = "ERROR_INVALID_PIN"
ERROR_INVALID_PASSWORD = "ERROR_INVALID_PASSWORD"
ERROR_INVALID_TOKEN = "ERROR_INVALID_TOKEN"
ERROR_ROLE_NOT_FOUND = "ERROR_ROLE_NOT_FOUND"
CUSTOMER_ROLE_NOT_EXIT = "CUSTOMER_ROLE_NOT_EXIT"
ERROR_NOTIFICATION_NOT_FOUND = "ERROR_NOTIFICATION_NOT_FOUND"
USER_ALREADY_EXIST = "USER_ALREADY_EXIST"
PIN_EXPIRED = "PIN_EXPIRED"
PIN_NOT_EXISTS = "PIN_NOT_EXISTS"
USER_CONNECTED_MERCHANT = "USER_CONNECTED_MERCHANT"
SAVE_IMAGE_TO_S3 = "SAVE_IMAGE_TO_S3"
